---
- name: FZF | remove ~/.fzf
  file:
    dest:  '{{ fzf.dir|default("~/.fzf") }}'
    state: absent
  when: is_ci

- name: FZF | fetch fzf repo
  git:
    repo: https://github.com/junegunn/fzf.git
    dest: '{{ fzf.dir }}'
    depth: 1
  when: fzf.dir
  register: update_fzf

- name: FZF | run install script
  command: '{{ fzf.dir }}/install --key-bindings --completion --no-update-rc'
  when: update_fzf.changed
