---
- name: ruby | get openssl dir
  shell: |
    openssl version -d | cut -d \" -f2
  register: openssl_dir
  when: ansible_distribution == 'Ubuntu'

- name: ruby | get readline dir
  command: |
    echo "/usr/include/readline"
  register: readline_dir
  when: ansible_distribution == 'Ubuntu'
