# Beets configuration --------------------------------------------------------

directory: /mnt/data/Documents/Music/library/
library: /mnt/data/Documents/Music/library.db

import:
    # write metadata to music files
    write: yes
    # move imported files from source to the music directory
    move: yes
    # use auto-tagging where possible
    autotag: yes
    # do not require confirmation on strong matches
    timid: no
    # controls whether interrupted imports should be resumed
    resume: ask
    # don't record which directories are already imported
    incremental: no
    # skip album in quiet mode when there is no strong recommendation
    quiet_fallback: skip
    # default action when selecting an action for a given match
    default_action: apply
    # a list of locale names to search for preferred aliases
    languages: ['nl', 'en']
    # show detailed information about each match it finds
    detail: no

# use the release-date of the original (first) release of an album?
original_date: no

# on multi-disk releases, assign track numbers for the whole album.
# If "per disk", make sure tracknames do not collide ("paths" setting).
per_disc_numbering: no

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]


# Paths ----------------------------------------------------------------------

# Paths and filenames for music files
# relative to music directory
paths:
    default: %asciify{$albumartist}/%asciify{$album}%aunique{}/$track %asciify{$title}
    singleton: Non-Album/%asciify{$artist}/%asciify{$title}
    comp: Compilations/%asciify{$album}%aunique{}/$track %asciify{$title}

# replace special characters in generated filenames
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''

path_sep_replace: _

# filename for the album art
art_filename: cover  # results in "cover.jpg"

max_filename_length: 0  # unlimited


# General --------------------------------------------------------------------

# use mutliple threads during import
threaded: yes
timeout: 5.0
verbose: no


# User Interface -------------------------------------------------------------

format_item: %upper{$artist} - $album - $track. $title
format_album: %upper{$albumartist} - $album
time_format: '%Y-%m-%d %H:%M:%S'
terminal_encoding: utf8

ui:
    color: yes
    terminal_width: 80
    length_diff_thresh: 10.0


# Auto Tagger ----------------------------------------------------------------

match:
    strong_rec_thresh: 0.1      # match 90% or better for auto import
    medium_rec_thresh: 0.25
    rec_gap_thresh: 0.25
    max_rec:
        missing_tracks: medium
        unmatched_tracks: medium
    distance_weights:
        source: 2.0
        artist: 3.0
        album: 3.0
        media: 1.0
        mediums: 1.0
        year: 1.0
        country: 0.5
        label: 0.5
        catalognum: 0.5
        albumdisambig: 0.5
        album_id: 5.0
        tracks: 2.0
        missing_tracks: 0.9
        unmatched_tracks: 0.6
        track_title: 3.0
        track_artist: 2.0
        track_index: 1.0
        track_length: 2.0
        track_id: 5.0
    preferred:
        countries: ['BE', 'GB|UK', 'US']
        media: ['CD']
        original_year: no
    ignored: []
    track_length_grace: 10
    track_length_max: 30


# Plugins --------------------------------------------------------------------

plugins: [
    convert,
    lyrics,
    fetchart,
    embedart,
    lastgenre,
    scrub,
    missing,
    duplicates,
    web
]
pluginpath:
  - ~/.dotfiles/beets


# Plugins Config -------------------------------------------------------------

convert:
    auto: no
    copy_album_art: yes
    never_convert_lossy_files: yes
    format: flac
    formats:
        flac:
            command: ffmpeg -i $source -y -acodec flac $dest
            extension: flac

lyrics:
    auto: yes
    fallback: ''

lastgenre:
    fallback: ''
    source: artist

fetchart:
    auto: yes
    maxwidth: 300
    cautious: true
    cover_names: cover folder
    sources: itunes *

embedart:
    auto: yes
    maxwidth: 300

scrub:
    auto: yes

missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no

duplicates:
    checksum: no  # expensive
