---
- name: nodejs | check nodenv
  shell: which nodenv
  register: which_nodenv
  ignore_errors: yes

- name: nodejs | install nodenv
  shell: anyenv install nodenv
  when: which_nodenv.rc > 0

- name: nodejs | get installed versions
  shell: nodenv versions
  register: installed_versions

- name: nodejs | install nodejs
  shell: nodenv install {{ item | quote }}
  when: |
    nodejs.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ nodejs.versions }}'

- name: nodejs | set global nodejs
  shell: nodenv global {{ nodejs.versions[0] | quote }}
  when: nodejs.versions

- name: nodejs | install npm packages
  npm:
    name:   '{{ item }}'
    global: yes
  with_items: '{{ nodejs.packages }}'
  when: nodejs.packages
