---
- name: nodejs | check nodenv
  command: |
    bash -lc 'which nodenv'
  register: which_nodenv
  ignore_errors: yes

- name: nodejs | install nodenv
  command: |
    bash -lc 'anyenv install nodenv'
  when: which_nodenv.rc > 0

- name: nodejs | get installed versions
  command: |
    bash -lc 'nodenv versions'
  register: installed_versions

- name: nodejs | install nodejs
  command: |
    bash -lc 'nodenv install {{ item | quote }}'
  when: |
    nodejs.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ nodejs.versions }}'

- name: nodejs | set global nodejs
  command: |
    bash -lc 'nodenv global {{ nodejs.versions[0] | quote }}'
  when: nodejs.versions

- name: nodejs | install npm packages
  npm:
    name:   '{{ item }}'
    global: yes
  with_items: '{{ nodejs.packages }}'
  when: nodejs.packages
