---
- name: vim | install dependency
  homebrew:
    name: ['lua', 'luajit']
    state: present

- name: vim | install neovim
  homebrew:
    name:  neovim
    state: latest

- name: vim | install Redis
  homebrew:
    name: redis
    state: present

- name: vim | start Redis
  command: |
    bash -lc 'brew services start redis'

- name: vim | set up a virtualenv for neovim
  block:
    - name: get python3 version
      command: |
        bash -lc 'pyenv versions | egrep -o "3.([0-9]{1,}\.)+[0-9]{1,}" | head -1 || true'
      register: python3_version

    - name: create virtualenv
      command: |
        bash -lc 'pyenv virtualenv {{ python.versions[0] | quote }} neovim3'
      args:
        creates: '{{ anyenv.envs_dir }}/pyenv/versions/neovim3' 

    - name: install python dependencies
      pip: 
        name: ['pynvim', 'jedi']
        virtualenv: '{{ anyenv.envs_dir }}/pyenv/versions/neovim3' 
